### ISSUE TITLE
PR: #7 Support for multiple selections

### ISSUE THREAD

**Issue by bgashler1** [bgashler1/vscode-htmltagwrap#10]
_From @hmigneron on October 31, 2016 15:40_

This pull request adds support for multiple selections.

Multiple selections work the same way single ones do : inline tag wrap is supported as well as multiline "block" tag wrap. We can also have a mix of the two.

![multi-selection](https://cloud.githubusercontent.com/assets/1261812/19860320/a7eca134-9f5e-11e6-83e2-4cc1de1013a7.gif)

The pull request also addresses the bug with empty selections (#6) which are now supported (both with single or multiple selections).

Thank you !

_Copied from original issue: Microsoft/vscode-htmltagwrap/pull/7_

**Comment by bgashler1** [comment]
_From @hmigneron on November 10, 2016 17:49_

Will anyone be able to review this ? @bgashler1 ?

**Comment by bgashler1** [comment]
Thanks @hmigneron for your contribution.  I'll be taking a look.

**Comment by bgashler1** [comment]
Merged in! Sorry for the delay.

**Comment by hmigneron** [comment]
Thank you !
