### ISSUE TITLE
Attach a different key-binding to invoke vscode-htmltagwrap

### ISSUE THREAD

**Issue by steven7mwesigwa** [bgashler1/vscode-htmltagwrap#14]
Since am using **"Alt + w"** to invoke the _"search & replace"_ feature of vscode, Am wondering if there is a separate setting i can use to attach a different key-binding to invoke your plugin.
_NOTE:_ i.e Pressing _"F7"_ to invoke plugin instead of using _"Alt + w"_

**Comment by bgashler1** [comment]
Hi @steven7mwesigwa ,

Yes, you can customize the keyboard shortcut to whatever you wish. To do so,

- Click on the gear icon on the bottom-left of VS Code and then on "Keyboard Shortcuts."
- In the "Search Keybindings" text field, type "htmltagwrap" which shows the wrapping command.
- Click on the pencil icon to edit this entry.
- Type whatever key or key combination you want (e.g. <kbd>F7</kbd>)

**Comment by bgashler1** [comment]
Alternatively, you can change the keyboard shortcut from another conflicting command (such as "toggleFindWholeWord" in Windows or a 3rd party extension's command that may conflict). To find conflicts with htmltagwrap's command, type in `Alt+W` (Windows, Linux) or `⌥ w` (Mac).

Hope this solves your problem. Feel free to reopen if you have more questions.
