### ISSUE TITLE
Undo Bug

### ISSUE THREAD

**Issue by nickfmc** [bgashler1/vscode-htmltagwrap#16]
There is an issue when you wrap code it defaults to a <p> tag then you change to say a div then you press ctrl +z to undo and one of the steps in the undo is changing your div back to a p tag and when this happens  a random div that my newly created tag is inside of also changes to a p tag.

**Comment by bgashler1** [comment]
I can't reproduce in the latest version, which has changed a lot since this issue was created. Let me know if it's still a problem, and if so, please include a sample of HTML that is affected so I can try to reproduce.
