### ISSUE TITLE
Last character on autocomplete not rendering

### ISSUE THREAD

**Issue by IronSean** [bgashler1/vscode-htmltagwrap#17]
When I select text and add a tag, then enter a component name and hit tab to autocomplete, the closing tag is missing the final character, like so:
`<MyComponentName>/*stuff*/</MyComponentNam>`

**Comment by JuhQ** [comment]
I have the same issue, +1

**Comment by bgashler1** [comment]
I can also reproduce. Thanks for submitting this issue. I'll look into it.

**Comment by m32po** [comment]
Same issue here. Worth to know that undoing (CTRL+Z) restores the missing char, but the second cursor (that one after the closing tag name) comes back.

**Comment by NushySC** [comment]
I have the same issue as well.

**Comment by PrincipalDev** [comment]
I have the same issue. A fix for this would make things so much easier and would be so greatly appreciated.

**Comment by alisonbuki** [comment]
+1 to fixing this pls

**Comment by IronSean** [comment]
I thought this has been fixed, but I realized I stopped using this extension and have been using the Emmet wrappers instead. They don't do autocomplete, but they do function, and I set it to the same key binding
```json
    {
        "key": "alt+w",
        "command": "editor.emmet.action.wrapWithAbbreviation"
    },
    {
        "key": "shift+alt+w",
        "command": "editor.emmet.action.wrapIndividualLinesWithAbbreviation"
    }
```

**Comment by genepine** [comment]
Now no need to use this extention
[Window Title]
Visual Studio Code 1.65.1
Emmet wrap commands are combined into one Emmet: Wrap with Abbeviation
https://stackoverflow.com/questions/67627819/vscode-missing-emmet-wrap-individual-lines-with-abbreviation

assign the short cut key . alt+w
abcd
efgh
li
```
<li>abcd
efgh
</li>
```
li*
```
<li>abcd</li>
<li>efgh</li>
```
