### ISSUE TITLE
Doesn't work on Mac version 1.25

### ISSUE THREAD

**Issue by BeMrTeal** [bgashler1/vscode-htmltagwrap#19]
I'm using version 1.25
MacOS 10.13.5

**Comment by bgashler1** [comment]
@bernardomed to help me reproduce this, here are a few questions...

1. When you press <kbd>Command</kbd> + <kbd>Shift</kbd>+ <kbd>P</kbd> and enter the command "Wrap in HTML Tags" does anything happen?
2. After trying this, can you Open Help > Toggle Developer Tools, then in the Console tab copy and paste the output there?
3. Does your issue happen still if you disable all your other extensions?
4. If so, which extensions do you currently have enabled in VS Code?
