### ISSUE TITLE
How to change default tag (from <p> to <div>)?

### ISSUE THREAD

**Issue by bgashler1** [bgashler1/vscode-htmltagwrap#2]
_From @kkorus on July 22, 2017 10:52_

How to change default tag while wrapping? I would like to change it from `<p></p>` to `<div></div>`.

_Copied from original issue: Microsoft/vscode-htmltagwrap#12_

**Comment by bgashler1** [comment]
_From @andreshg112 on September 15, 2017 1:24_

I'm waiting for this too!

**Comment by bgashler1** [comment]
_From @korn3l on September 15, 2017 11:49_

There is already a PR for this : #13

**Comment by bgashler1** [comment]
_From @johndangerstorey on October 24, 2017 17:19_

Cool, hopefully it allows for a user to not pic ANY default tag, just leave blinking cursor as well :)  Thanks for the awesome plugin!

**Comment by bgashler1** [comment]
@kkorus this has been fixed in the latest release. Please reopen if you're still having this issue after updating.

Thanks!

**Comment by kkorus** [comment]
@bgashler1  What settings value I need to change?

**Comment by bgashler1** [comment]
@kkorus if, for example, you want a ‘div’ instead of the default tag, you can add this setting,
‘’’
{
   "htmltagwrap.tag": "div”
}
‘’’
