### ISSUE TITLE
Doesn't work for me on High Sierra

### ISSUE THREAD

**Issue by autodonncha** [bgashler1/vscode-htmltagwrap#21]
I don't know why, but when I hit the Opt + W shortcut, I get some strange behaviour. Perhaps it's a conflict, any ideas?
![2018-09-27 14 02 11](https://user-images.githubusercontent.com/40022007/46147654-fd2afc80-c25d-11e8-99af-829abf83ead4.gif)

**Comment by bgashler1** [comment]
I can't seem to reproduce this.

Which version of VS Code are you using?
Does it happen still if you disable your other extensions?
If so, which extensions do you currently have enabled in VS Code?
