### ISSUE TITLE
Deleting 2nd Part of selection after wrap

### ISSUE THREAD

**Issue by dlbone** [bgashler1/vscode-htmltagwrap#26]
When I wrap text with a shortcut, about 30% of the time it will delete the p in the closing tag. I have disabled all other plugins in VS Code and this is still happening. Any help would be appreciated.
<img width="170" alt="Screen Shot 2019-03-26 at 6 52 43 PM" src="https://user-images.githubusercontent.com/8334124/55044658-6bc3f980-4ff8-11e9-843a-df0338aad802.png">

**Comment by volkerdobler** [comment]
Same for me - any solution so far? 
(by the way - pressing CTRL-Z/undo - helps getting the closing tag back, so the problem seems to be a second invisible step which deletes the final tag. but this is not the solution I am looking for)

**Comment by dlbone** [comment]
I do the same thing, although you lose some of the intelligence with continuing to write attributes. Haven't found another solution yet.

**Comment by bgashler1** [comment]
Should be fixed in latest release. Please reopen if not.

**Comment by dlbone** [comment]
@bgashler1 amazing thank you
