### ISSUE TITLE
anchor around email

### ISSUE THREAD

**Issue by MichaelLSmith** [bgashler1/vscode-htmltagwrap#27]
When you try to wrap an email address with an anchor tag, it first puts mailto:name@mailserver.com in the href attribute, but after pressing enter to accept it, it ends up as an empty href. It's a small thing, but would be really helpful if it worked properly.

Thanks for the amazing addon.

**Comment by bgashler1** [comment]
I can’t reproduce this issue. This extension’s code does not attempt to create an href attribute for you but does support you pressing spacebar to create one on the opening tags. Try disabling all other extensions and see if you have a conflict with keyboard shortcuts for `Alt + W`

**Comment by bgashler1** [comment]
If you can repro still let me know how you do it  and reopen
