### ISSUE TITLE
pressing space with autoDeselectClosingTag removes part of the tag

### ISSUE THREAD

**Issue by Norlandz** [bgashler1/vscode-htmltagwrap#34]
### To produce the bug
1. you have a sentence: `a more detailed look`
2. `autoDeselectClosingTag = true`
3. select a string `detailed`
4. press `alt+w` -> wrapping the string: `a more <p>detailed</p> look` -- good
5. type `span` ->  `a more <span>detailed</span> look` -- good
6. press `space` -> `a more <spn >detailed</spn > look` -- **WRONG**, you can see it removes part of the tag

**Comment by aaroncrawford** [comment]
Getting similar behavior.  Glad it's not just me.  See attached GIF of this behavior
![Screen Capture on 2023-02-14 at 15-19-06](https://user-images.githubusercontent.com/3203500/218865683-970dee1f-213c-46be-b4ed-73ea3ab3c429.gif)

**Comment by pccily** [comment]
一样的bug，什么时候可以修复？？？ 。。。。。。。。。

**Comment by Norlandz** [comment]
### solution (workaround) (Ahk)

1. Turn off the `autoDeselectClosingTag` 
1. Press `Esc` twice to remove the `Caret (Cursor)` at the `Closing Tag` 
1. Type a `Space` 

An Ahk implementation to automate this:

- note: this _overwrites all `alt+w`_ hotkey you have in Vscode,
  if you press `alt+w` at the wrong place, it will have undesired effect -- ie: press space will `SendInput, {Esc 2}{Space}`
  (if you know ahk, you should be already aware of this)

```ahk
#NoEnv

; autoexecutesectionAHK_Vscode:

Hotkey, IfWinActive, ahk_exe Code.exe
Hotkey, $Space, Off
Hotkey, IfWinActive

; return


#IfWinActive, ahk_exe Code.exe

; ########

; #>> vscode-htmltagwrap
;; <strike> SetTimer, label_waitForWhiteSpace_and_goToOpeningTag, 10 ;; dk can Timer do? or keyboard hook?... too complex? 

$!w::
{
SendInput, !w

Hotkey, IfWinActive, ahk_exe Code.exe
Hotkey, $Space, On
Hotkey, IfWinActive

return
}

$Space::
{
SendInput, {Esc 2}{Space}

Hotkey, IfWinActive, ahk_exe Code.exe
Hotkey, $Space, Off
Hotkey, IfWinActive

return
}

#IfWinActive
```

**Comment by m-stanczak** [comment]
Anyone fix it ?:) For now I just uninstall plugin but I miss it everyday ;)

**Comment by oldo** [comment]
Yes, this is a shame. It's one of my most used extensions!

**Comment by danulqua** [comment]
Any update on this issue?

**Comment by aaroncrawford** [comment]
@bgashler1 Any possibility in fixing?

**Comment by ack4192** [comment]
I have the same issue. I hope this would be fixed.

**Comment by danulqua** [comment]
I've been using this workaround (see screenshot which works better imo.  

![CleanShot 2023-03-22 at 20 56 03@2x](https://user-images.githubusercontent.com/38916225/227008646-9e496386-1aee-4796-82f5-1629236760ca.jpg)

**Comment by Rayboris** [comment]
I have the same problem. Hopefully it will be fixed

**Comment by bgashler1** [comment]
Looking into this issue now.

**Comment by bgashler1** [comment]
Fix will be deployed in 0.0.8 release coming in a bit

**Comment by aaroncrawford** [comment]
Thanks Brad

**Comment by ack4192** [comment]
I really appreciate it!!!

**Comment by Norlandz** [comment]
@bgashler1 

There is a problem. 

For the `space` (or `tab`)  key: 
- it **only works** when you **only use `p`** as `The default HTML tag to insert when using htmltagwrap.`
- but when you...
  1. use **`div` or others** as `The default HTML tag to insert when using htmltagwrap.`
  1. you must **type in a letter or tab the autocompletion first**, then tab again.
  2. otherwise, the tag will be replaced by a `space`

https://github.com/user-attachments/assets/d661bbbe-6cf8-4de9-9c54-d9864fa26695
