### ISSUE TITLE
Wrap current line if no selection is present

### ISSUE THREAD

**Issue by bgashler1** [bgashler1/vscode-htmltagwrap#6]
_From @greyvugrin on December 22, 2016 21:27_

This could speed up development by allowing users to skip the highlighting portion if they know they want to wrap all text in the line where the cursor is located

_Copied from original issue: Microsoft/vscode-htmltagwrap#8_

**Comment by bgashler1** [comment]
_From @johndangerstorey on October 24, 2017 17:18_

+1

**Comment by bgashler1** [comment]
This is now in the latest release `0.0.6`.

**Comment by greyvugrin** [comment]
@bgashler1 woohoo!
